### ISSUE TITLE
Crear cuenta en HelpScout

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#1]
Crear un cuenta en HelpScout y compartirla con todos los colaboradores.

/cc @evazquez-gstd @aromero-gstd

**Comment by evazquez-gstd** [comment]
Datos para acceder a HelpScout.

Email: evazquez@globalstd.com
Password: Software@2017

Log In: https://secure.helpscout.net/members/login/?action=logout
