### ISSUE TITLE
Diseñar pantalla "Mailbox Details"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#10]
Usando la plantilla "limitless" cree una página web de tal manera que se mire similar a la siguiente imagen:

![captura de pantalla 2016-12-09 a las 16 11 16](https://cloud.githubusercontent.com/assets/22350992/21066270/59e7949a-be2a-11e6-9df4-d63c3384ef32.png)

**Comment by ivaldivia** [comment]
![hscout_mailbox_detail](https://cloud.githubusercontent.com/assets/22351217/21105238/1dcdb292-c04f-11e6-9408-66036a35acd9.png)

**Comment by ivaldivia** [comment]
@fmendoza-gstd cuales son las detalles a cambiar?

**Comment by fmendoza-gstd** [comment]
![1dcdb292-c04f-11e6-9408-66036a35acd9](https://cloud.githubusercontent.com/assets/22350992/21105776/196dae58-c051-11e6-89aa-7327086d5779.png)

**Comment by ivaldivia** [comment]
![hscout_mailbox_detail2](https://cloud.githubusercontent.com/assets/22351217/21112280/dc2d9098-c06a-11e6-9134-e5678e7d613e.png)
