### ISSUE TITLE
Diseñar pantalla "User Details"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#11]
Usando la plantilla "limitless" cree una página web de tal manera que se mire similar a la siguiente imagen:

![captura de pantalla 2016-12-09 a las 16 16 18](https://cloud.githubusercontent.com/assets/22350992/21066381/e3a6a518-be2a-11e6-8ec8-fb1820d60ce0.png)

**Comment by ivaldivia** [comment]
![hscout_profile_detail](https://cloud.githubusercontent.com/assets/22351217/21107731/5cc61dbe-c058-11e6-9d55-0252e6dfc660.png)
![hscout_profile_detail2](https://cloud.githubusercontent.com/assets/22351217/21107735/618f9f00-c058-11e6-8029-d5de8b87c44d.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
