### ISSUE TITLE
Diseñar pantalla "Spam Settings"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#12]
Usando la plantilla "limitless" cree una página web de tal manera que se mire similar a la siguiente imagen:

![captura de pantalla 2016-12-12 a las 9 13 21](https://cloud.githubusercontent.com/assets/22350992/21104211/4bb93c7a-c04b-11e6-92de-0cafb967516d.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21108589/55437d7c-c05b-11e6-9145-8819f4fb7d89.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
