### ISSUE TITLE
Diseñar pantalla "Notifications"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#13]
Usando la plantilla "limitless" cree una página web de tal manera que se mire similar a la siguiente imagen:

![captura de pantalla 2016-12-12 a las 9 15 10](https://cloud.githubusercontent.com/assets/22350992/21104284/8f4f94ac-c04b-11e6-90b0-b45f1d87e82e.png)

**Comment by ivaldivia** [comment]
![hscout_notifications](https://cloud.githubusercontent.com/assets/22351217/21110103/98ebb0f2-c061-11e6-9562-71ac7b08ca61.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
