### ISSUE TITLE
Diseñar pantalla "Auto Reply"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#14]
Usando la plantilla "limitless" cree una página web de tal manera que se mire similar a la siguiente imagen:

![captura de pantalla 2016-12-12 a las 9 16 49](https://cloud.githubusercontent.com/assets/22350992/21104342/cd8c70f0-c04b-11e6-8ef1-4d1ac83768c2.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21107492/85035996-c057-11e6-8766-250dbc576d6c.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21107750/69edc5fa-c058-11e6-84b4-0f72c3e24891.png)
