### ISSUE TITLE
Extender vista "Company"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#15]
Heredar la vista por defecto de "Company" para agregar los nuevos campos sobre un nuevo TAB cuyo nombre debe ser "HelpScout":

![captura de pantalla 2016-12-12 a las 10 09 10](https://cloud.githubusercontent.com/assets/22350992/21106321/48d351fa-c053-11e6-8431-9e201c333fde.png)

**Comment by ivaldivia** [comment]
Vista extendida de company
id="company_view_form_inherit_hscout"

![inherit company](https://cloud.githubusercontent.com/assets/22351217/21156018/ef9d9496-c139-11e6-852f-7afd1492c1a5.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
