### ISSUE TITLE
Extender vista "Contact"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#16]
Extender vista por defecto "Contact" para agregar campos del modelo "User", los campos deben ser agregados en un nuevo tab como se muestra en la siguiente imagen:

![captura de pantalla 2016-12-12 a las 10 20 12](https://cloud.githubusercontent.com/assets/22350992/21106729/b8dad2f6-c054-11e6-9536-19db46a72e80.png)

**Comment by ivaldivia** [comment]
Ya se agregó el tab en partner para help scout

id="partner_view_form_inherit_hscout"

**Comment by ivaldivia** [comment]
![contact inherit](https://cloud.githubusercontent.com/assets/22351217/21155050/3f28cffc-c136-11e6-8034-fc535c4ba270.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
