### ISSUE TITLE
Extender vista "Project"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#17]
Extender vista por defecto "Project" para agregar los campos del modelo "Mailbox", los campos deben ser agregados en un nuevo tab como se muestra en la siguiente imagen:

![captura de pantalla 2016-12-12 a las 10 26 02](https://cloud.githubusercontent.com/assets/22350992/21106929/84a4fe70-c055-11e6-8528-a9c094938cad.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21163732/62f37d00-c15a-11e6-885c-54a24b4a0ecb.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
