### ISSUE TITLE
Homologar pantallas

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#18]
La finalidad de esta tarea es homologar todas las plantillas de tal manera que los elementos comunes tengan el mismo estilo y diseño. Como la tarea es un poco larga y compleja de describir en un primer comentario, iniciaremos con las siguientes dos actividades:

- [x] Dar formato a todas las plantillas con un nivel de sangría de 4.
- [x] Anexar imágenes del diseño final de las nuevas plantillas (con estas imágenes indicaremos con exactitud lo que hay que modificar).

**Comment by evazquez-gstd** [comment]
Anexo Plantilla "Mailbox"

![imagen](https://cloud.githubusercontent.com/assets/22351598/21119797/c44adc0a-c089-11e6-9898-4d59acd62f88.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21119906/51d4d896-c08a-11e6-9b66-1ea1cdbcdace.png)

Anexo Plantilla "Users"

![imagen](https://cloud.githubusercontent.com/assets/22351598/21119941/79585348-c08a-11e6-96ec-37deb81a83a1.png)

Anexo Plantilla "Login"

![imagen](https://cloud.githubusercontent.com/assets/22351598/21119964/972a0196-c08a-11e6-8401-13d5eecb0830.png)

Anexo Plantilla "Mailboxes"

![imagen](https://cloud.githubusercontent.com/assets/22351598/21119994/bcd927b4-c08a-11e6-913e-3f18e2da6626.png)


Anexo Plantilla "Edit Mailbox"

![imagen](https://cloud.githubusercontent.com/assets/22351598/21120044/fdbdedfa-c08a-11e6-9325-e338ac73a164.png)

Anexo Plantilla "Profile"

![imagen](https://cloud.githubusercontent.com/assets/22351598/21120076/2d18d920-c08b-11e6-9bef-bd41a192a4bc.png)

Anexo Plantilla "Notifications"

![imagen](https://cloud.githubusercontent.com/assets/22351598/21120118/618fa71a-c08b-11e6-943a-6d9a17fa39f7.png)

Anexo Plantilla "Auto Reply"

![imagen](https://cloud.githubusercontent.com/assets/22351598/21120167/9ed95b98-c08b-11e6-9ad5-cc1fb827ced8.png)

Anexo Plantilla "Dashboard"

![imagen](https://cloud.githubusercontent.com/assets/22351598/21120187/b831e0a6-c08b-11e6-8ab7-382eb61db145.png)

Anexo Plantilla "Message Detail"

![imagen](https://cloud.githubusercontent.com/assets/22351598/21120243/fad3b1a0-c08b-11e6-8c43-899af6a7d800.png)

Anexo Plantilla "Edit Company"

![imagen](https://cloud.githubusercontent.com/assets/22351598/21120269/15e6999e-c08c-11e6-8af6-2c1100b802bf.png)

Anexo Plantilla "Spam Settings"

![imagen](https://cloud.githubusercontent.com/assets/22351598/21120328/598169e0-c08c-11e6-9035-b2b46f637451.png)

Ya se aplico formato a las plantillas.

**Comment by fmendoza-gstd** [comment]
@evazquez-gstd 
Corregir las siguientes observaciones:

- La barra de menú superior para todas las pantallas debe ser como la de la siguiente imagen:  ![imagen](https://cloud.githubusercontent.com/assets/22351598/21120167/9ed95b98-c08b-11e6-9ad5-cc1fb827ced8.png)

- Los menu flotantes como el de la siguiente imagen tienen un estilo incorrecto, los menu flotantes debe de verse como el menu mostrado al hacer click en "Victoria":  ![imagen](https://cloud.githubusercontent.com/assets/22351598/21120044/fdbdedfa-c08a-11e6-9325-e338ac73a164.png)

- Eliminar los pie de página de todas las plantillas.  
![bcd927b4-c08a-11e6-913e-3f18e2da6626](https://cloud.githubusercontent.com/assets/22350992/21120854/023bee14-c08f-11e6-81f7-305dfdaaab47.png)

- Corregir los indicadores de la siguiente plantilla:  ![fad3b1a0-c08b-11e6-8c43-899af6a7d800](https://cloud.githubusercontent.com/assets/22350992/21121026/c0bb1e1e-c08f-11e6-8fcd-a80771e176e1.png)

- La barra lateral izquierda para todas las plantillas deben compartir los siguientes criterios:   ![fdbdedfa-c08a-11e6-9325-e338ac73a164](https://cloud.githubusercontent.com/assets/22350992/21121139/5f996d06-c090-11e6-942e-e2b7cafedbef.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21151425/1685baf0-c128-11e6-9175-7cbce10cf113.png)

![imagen](https://cloud.githubusercontent.com/assets/22351598/21151438/201e2fa2-c128-11e6-9ede-90c5a85781fa.png)

![imagen](https://cloud.githubusercontent.com/assets/22351598/21151447/2a5020f2-c128-11e6-8d39-17a5b8965b6e.png)


![imagen](https://cloud.githubusercontent.com/assets/22351598/21151469/3e0099e2-c128-11e6-91c7-cac11888a232.png)


![imagen](https://cloud.githubusercontent.com/assets/22351598/21151490/4eeef550-c128-11e6-98fe-23999cd46bcf.png)


![imagen](https://cloud.githubusercontent.com/assets/22351598/21151497/583f42cc-c128-11e6-9e24-c2626e7ea49c.png)


![imagen](https://cloud.githubusercontent.com/assets/22351598/21151512/65e8dcee-c128-11e6-8128-50a6586029f9.png)


![imagen](https://cloud.githubusercontent.com/assets/22351598/21151534/7bc41592-c128-11e6-8b66-caa1d903a1b8.png)


![imagen](https://cloud.githubusercontent.com/assets/22351598/21151545/8868f1c8-c128-11e6-8d48-a0104b64d431.png)


![imagen](https://cloud.githubusercontent.com/assets/22351598/21151564/9d27dfb6-c128-11e6-9565-426d21bef7dc.png)


![imagen](https://cloud.githubusercontent.com/assets/22351598/21151585/ace2770e-c128-11e6-84dd-91245254f6e0.png)


![imagen](https://cloud.githubusercontent.com/assets/22351598/21151609/be02ac48-c128-11e6-96ca-11b752e6b084.png)

Anexo screenshot de cambios

**Comment by fmendoza-gstd** [comment]
God Job! 👍
