### ISSUE TITLE
Diseñar pantalla "Mailbox"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#2]
Usando la plantilla "limitless" cree una página web de tal manera que se mire similar a la siguiente imagen:

![captura de pantalla 2016-12-08 a las 15 29 12](https://cloud.githubusercontent.com/assets/22350992/21028562/50cd5acc-bd5b-11e6-8222-3548b5f14873.png)

Solo es necesario respetar la estructura y el contenido.

**Comment by fmendoza-gstd** [comment]
Remover columnas innecesarias y agregar los TAGS a las conversaciones.

**Comment by ivaldivia** [comment]
![hscout_mailbox](https://cloud.githubusercontent.com/assets/22351217/21058882/ae2a3852-be05-11e6-9047-8b03ba1f310d.png)

**Comment by fmendoza-gstd** [comment]
@ivaldivia
La siguiente imagen contiene las observaciones:

![ae2a3852-be05-11e6-9047-8b03ba1f310d](https://cloud.githubusercontent.com/assets/22350992/21059525/69f80508-be08-11e6-87ac-212e01582c5b.png)

**Comment by ivaldivia** [comment]
![hscout_mailbox2](https://cloud.githubusercontent.com/assets/22351217/21060573/b440e56c-be0d-11e6-8ac4-19da732ebee9.png)
