### ISSUE TITLE
Crear website page "Company"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#25]
Agregar sobre Odoo el website layout de la siguiente plantilla:

![imagen](https://cloud.githubusercontent.com/assets/22351598/21068884/8b8c6470-be3a-11e6-8d1c-157fddfb6b95.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21164800/0027035c-c161-11e6-9b58-f36f06884114.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
