### ISSUE TITLE
Mejorar páginas web

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#26]
Esta es una actividad de varias etapas, en esta etapa se requiere lo siguiente:

- Obtener todas las direcciones url de las páginas web.

**Comment by evazquez-gstd** [comment]
http://localhost:9069/page/mailbox 
id = website.mailbox

http://localhost:9069/page/conversation
id = website.conversation

http://localhost:9069/page/mailboxes
id = website.mailboxes

http://localhost:9069/page/users
id = website.users

http://localhost:9069/page/spam_settings
id = website.spam_settings

http://localhost:9069/page/profile
id = website.profile

http://localhost:9069/page/company
id = website.company

http://localhost:9069/page/autoreply
id = website.autoreply

**Comment by fmendoza-gstd** [comment]
@evazquez-gstd 
Cambiar la url de las siguiente páginas:

- mailboxes => settings/mailboxes
- spam_settings => settings/spam
- company => settings/company
- profile => users/profile
- autoreply => settings/company/autoreply

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21192523/82e16c32-c1ee-11e6-8ed5-0e97143032c8.png)

![imagen](https://cloud.githubusercontent.com/assets/22351598/21192558/97a62612-c1ee-11e6-8214-e8372ac8b1c4.png)

![imagen](https://cloud.githubusercontent.com/assets/22351598/21192573/a66ce6c2-c1ee-11e6-9d95-79795c39d9a7.png)

![imagen](https://cloud.githubusercontent.com/assets/22351598/21192717/269cbfd4-c1ef-11e6-9a01-117537bc78d6.png)

![imagen](https://cloud.githubusercontent.com/assets/22351598/21192746/37681192-c1ef-11e6-8953-5bc4747fea18.png)

**Comment by fmendoza-gstd** [comment]
@evazquez-gstd 
Actualizar los links (donde pueda hacerse) de todas la página de tal forma que te lleve a la página correcta, por ejemplo vea la siguiente imagen:

![captura de pantalla 2016-12-14 a las 11 34 45](https://cloud.githubusercontent.com/assets/22350992/21193326/85f942d4-c1f1-11e6-8017-abcbb14c7642.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21196891/0b7dd8d6-c1ff-11e6-9a22-6fc21fd98abf.png)

**Comment by fmendoza-gstd** [comment]
@evazquez-gstd 
La barra de menú superior se repite en todas las plantillas, extraerla como una sub-plantilla y usar qweb para incluirla en todas las páginas.

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21202810/8983e89a-c215-11e6-954f-a2b2ac41e4de.png)

![imagen](https://cloud.githubusercontent.com/assets/22351598/21202838/a7db4cac-c215-11e6-8cf0-ff7467ae6b49.png)

![imagen](https://cloud.githubusercontent.com/assets/22351598/21202849/bafd21f2-c215-11e6-985b-4e402cd66776.png)

**Comment by fmendoza-gstd** [comment]
@evazquez-gstd 
Muchos links siguen estando incorrectos, por ejemplo "Mailbox" no hace nada y así hay otros.

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
