### ISSUE TITLE
Crear website page "Dashboard"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#27]
Agregar sobre Odoo el website layout de la siguiente plantilla:

![imagen](https://cloud.githubusercontent.com/assets/22351598/21067275/b3d4ca7c-be2f-11e6-81f9-80d4d13b0b98.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21234008/e169dde8-c2b6-11e6-8809-37d4034d734f.png)

**Comment by fmendoza-gstd** [comment]
@evazquez-gstd 
Corregir las siguientes observaciones:

![e169dde8-c2b6-11e6-8809-37d4034d734f](https://cloud.githubusercontent.com/assets/22350992/21235430/5102afc2-c2bc-11e6-8e3a-cc4e4e53b13d.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21236720/d2c5df0c-c2c1-11e6-861a-14175a100c97.png)

**Comment by fmendoza-gstd** [comment]
@evazquez-gstd 
Corregir las siguientes observaciones:

![d2c5df0c-c2c1-11e6-861a-14175a100c97](https://cloud.githubusercontent.com/assets/22350992/21237243/b696858c-c2c3-11e6-81ed-023dd618f4ef.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21237912/8910ccf0-c2c6-11e6-85dc-e8f7d19784a0.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
