### ISSUE TITLE
Crear website page "Notifications" 

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#28]
Agregar sobre Odoo el website layout de la siguiente plantilla:

![hscout_notifications](https://cloud.githubusercontent.com/assets/22351217/21110103/98ebb0f2-c061-11e6-9562-71ac7b08ca61.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21204295/65cf5838-c21c-11e6-98da-198a359c7948.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
