### ISSUE TITLE
Crear website page "Auto Reply"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#29]
Agregar sobre Odoo el website layout de la siguiente plantilla:

![imagen](https://cloud.githubusercontent.com/assets/22351598/21107750/69edc5fa-c058-11e6-84b4-0f72c3e24891.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21190352/13df54cc-c1e7-11e6-94ed-59ad71841c14.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
