### ISSUE TITLE
Diseñar pantalla "Detalle de Mensaje"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#3]
Usando la plantilla "limitless" cree una página web que sea similar a la siguiente imágen:

![captura de pantalla 2016-12-08 a las 15 34 10](https://cloud.githubusercontent.com/assets/22350992/21028696/f202989e-bd5b-11e6-997c-b7ac507f3314.png)

Solo es necesario respetar la estructura y el contenido.

**Comment by fmendoza-gstd** [comment]
@evazquez-gstd  realizar los siguientes cambios:

1. Trabajar en la sección "Información del Cliente" que se mire similar al original.
2. Remover botones innecesarios.
3. Trabajar en la barra de menu superior, que se mire como el original

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21056213/4540d22a-bdfa-11e6-96cd-806ae2aeb432.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21059449/1efc467c-be08-11e6-8a19-19e17048b067.png)

**Comment by fmendoza-gstd** [comment]
@evazquez-gstd 
Las observaciones están en la siguiente imagen:

![1efc467c-be08-11e6-8a19-19e17048b067](https://cloud.githubusercontent.com/assets/22350992/21059897/573aa81a-be0a-11e6-8277-4048d68e05be.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21062409/63604f12-be16-11e6-8d13-ae866d2ce9ac.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21064746/3ba94828-be22-11e6-8f3a-e9681159fd87.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21064862/f6fa42a8-be22-11e6-88d4-be4ff72e8d4c.png)
