### ISSUE TITLE
Desplegar datos en página "Users"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#33]
Usar el api de Odoo para desplegar datos en la siguiente página:

![hscout_users](https://cloud.githubusercontent.com/assets/22351217/21065689/4e80d6a0-be27-11e6-8fed-5ff0839c3970.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21246758/57e5d4a2-c2f0-11e6-935d-8bfd21adc05b.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
