### ISSUE TITLE
Desplegar datos en página "User Details"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#34]
Usar el api de Odoo para desplegar datos en la siguiente página:

![hscout_profile_detail](https://cloud.githubusercontent.com/assets/22351217/21107731/5cc61dbe-c058-11e6-9d55-0252e6dfc660.png)
![hscout_profile_detail2](https://cloud.githubusercontent.com/assets/22351217/21107735/618f9f00-c058-11e6-8029-d5de8b87c44d.png)

**Comment by evazquez-gstd** [comment]
1.- No ubiqué información de timezone para desplegar en plantilla.
2.-  No ubiqué información de roles para desplegar en plantila.

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
