### ISSUE TITLE
Desplegar datos en página "Mailbox"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#35]
Usar el api de Odoo para desplegar datos en la siguiente página:

![hscout_mailbox2](https://cloud.githubusercontent.com/assets/22351217/21060573/b440e56c-be0d-11e6-8ac4-19da732ebee9.png)

**Comment by ivaldivia** [comment]
Falto el contador de Draft y el contador de Spam, ya que no hay una etapa (project.task.type) para ellos en estos momentos

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
