### ISSUE TITLE
Desplegar datos en página "Conversation"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#36]
Usar el api de Odoo para desplegar datos en la siguiente página:

![imagen](https://cloud.githubusercontent.com/assets/22351598/21064862/f6fa42a8-be22-11e6-88d4-be4ff72e8d4c.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21363474/5a732c72-c6b2-11e6-9c5d-a13a685bea9c.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
