### ISSUE TITLE
Diseñar pantalla "Usuarios"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#4]
Usando la plantilla "limitless" cree una página web que sea similar a la siguiente imagen:

![captura de pantalla 2016-12-08 a las 15 37 40](https://cloud.githubusercontent.com/assets/22350992/21028789/5856a1e4-bd5c-11e6-9223-abd7f48b0b4f.png)

Solo es necesario respetar la estructura y el contenido.

**Comment by ivaldivia** [comment]
![hscout_users](https://cloud.githubusercontent.com/assets/22351217/21065689/4e80d6a0-be27-11e6-8fed-5ff0839c3970.png)
