### ISSUE TITLE
Diseñar pantalla "Dashboard"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#5]
Usando la plantilla "limitless" cree una página web de tal manera que se mire similar a la siguiente imagen:

![captura de pantalla 2016-12-08 a las 15 40 52](https://cloud.githubusercontent.com/assets/22350992/21028866/ba6a4642-bd5c-11e6-9484-db2810d950bd.png)

Solo es necesario respetar la estructura y el contenido.

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21067233/80f65e18-be2f-11e6-88b1-3fbb6646a23e.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21067275/b3d4ca7c-be2f-11e6-81f9-80d4d13b0b98.png)
