### ISSUE TITLE
Diseñar pantalla "Edit Company"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#6]
Usando la plantilla "limitless" cree una página web de tal manera que se mire similar a la siguiente imagen:

![captura de pantalla 2016-12-08 a las 16 12 14](https://cloud.githubusercontent.com/assets/22350992/21029822/35c52362-bd61-11e6-8168-b7dc0178ebde.png)

Solo es necesario respetar la estructura y el contenido.

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21068485/f2e7d5d0-be37-11e6-9d70-f6f7c02ee26a.png)

**Comment by fmendoza-gstd** [comment]
@evazquez-gstd 
Resolver los siguiente errores:

![f2e7d5d0-be37-11e6-9d70-f6f7c02ee26a](https://cloud.githubusercontent.com/assets/22350992/21068666/372aaece-be39-11e6-8cdf-0eb4a544ac64.png)

**Comment by evazquez-gstd** [comment]
![imagen](https://cloud.githubusercontent.com/assets/22351598/21068884/8b8c6470-be3a-11e6-8d1c-157fddfb6b95.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
