### ISSUE TITLE
Diseñar pantalla "Log In"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#7]
Usando la plantilla "limitless" cree una página web de tal manera que se mire similar a la siguiente imagen:

![captura de pantalla 2016-12-08 a las 17 49 14](https://cloud.githubusercontent.com/assets/22350992/21032380/c6c9a13c-bd6e-11e6-90e8-1467e866bb75.png)

**Comment by ivaldivia** [comment]
![hscout_login](https://cloud.githubusercontent.com/assets/22351217/21067195/588c356a-be2f-11e6-9e6b-da4ce76848e6.png)
