### ISSUE TITLE
Diseñar pantalla "Mailboxes"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-erp#9]
Usando la plantilla "limitless" cree una página web de tal manera que se mire similar a la siguiente imagen:

![captura de pantalla 2016-12-09 a las 16 08 28](https://cloud.githubusercontent.com/assets/22350992/21066176/bfccec66-be29-11e6-8e73-947b3d0235fb.png)

**Comment by ivaldivia** [comment]
![hscout_mailboxes](https://cloud.githubusercontent.com/assets/22351217/21067549/773b8356-be31-11e6-8fce-1d173f2bf486.png)
